%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 29-Jul-2026 17:57:27
                     ConfigInfos.Version = '25.2.0.3312555 (R2025b) Update 6';
                   ConfigInfos.SessionID = 'ConfiguredVirtualVehicle.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\Autotronica\MATLAB\Projects\examples';
                    ConfigInfos.ProjPath = 'C:\Users\Autotronica\MATLAB\Projects\examples\VirtualVehicle7\VirtualVehicle';
                 ConfigInfos.SessionName = 'ConfiguredVirtualVehicle';
                 ConfigInfos.XmlPathText = 'C:\Users\Autotronica\MATLAB\Projects\examples\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 1EM';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 3DOF Longitudinal';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 3DOF Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Front Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '1EM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'moreno';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'No Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'No Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'No Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'No IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'No Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Single-Speed Transmission 1EM';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 1EM with BMS';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '1836';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{1}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{1}.Driver = 'Longitudinal Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnSimTime';
       ConfigInfos.TestPlan{1}.Data{1,2} = '2474';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnLongVelUnit';
       ConfigInfos.TestPlan{1}.Data{2,2} = 'mph';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{3,2} = '0';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'DriverPreviewDist';
       ConfigInfos.TestPlan{1}.Data{4,2} = '4';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'DriverTimeConst';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0.3';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'DriverAeroRes';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0.5';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'DriverDrivelineRes';
       ConfigInfos.TestPlan{1}.Data{8,2} = '75';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'DriverRollRes';
       ConfigInfos.TestPlan{1}.Data{9,2} = '200';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{10,2} = '15000';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattCurr',...
'Battery.BattInfo.BattPwr',...
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattTemp',...
'Battery.BattInfo.BattVolt',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'Driver.SteerFdbk',...
'EM.EMSpd',...
'EM.EMTrq',...
};

%% Finish
